sbp/pending-check/run.py

By default the container will submit 4 jobs and exit, it can be overriden by setting the MAX_STARTS environment var

Limit the number of simultaneous job submissions using MAX_STARTS

---

cluster/src/main/java/com/hartwig/pipeline/Arguments.java
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/alignment/DataprocLogComponent.java
cluster/src/main/java/com/hartwig/pipeline/report/FullSomaticResults.java
cluster/src/main/java/com/hartwig/pipeline/resource/Resource.java
cluster/src/main/java/com/hartwig/pipeline/storage/RuntimeBucket.java
cluster/src/main/java/com/hartwig/pipeline/storage/StorageProvider.java
cluster/src/test/java/com/hartwig/pipeline/alignment/DataprocLogComponentTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/germline/GermlineCallerTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/somatic/SomaticCallerTest.java
cluster/src/test/java/com/hartwig/pipeline/storage/RuntimeBucketTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/amber/AmberTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/cobalt/CobaltTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/healthcheck/HealthCheckerTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/purple/PurpleTest.java

Passed in as an argument, when present all runtime buckets will set the
kms property on creation (note will not change old buckets already using
Google keys).
Also necessary to increase storage timeouts and use the .getResult() to
ensure the the entire copy operation completes.

DEV-821 Add option to specify CMEK

---

cluster/src/main/java/com/hartwig/pipeline/metadata/SetMetadataApiProvider.java
cluster/src/main/java/com/hartwig/pipeline/transfer/SbpFileTransfer.java
cluster/src/main/java/com/hartwig/pipeline/transfer/SbpFileTransferProvider.java
cluster/src/test/java/com/hartwig/pipeline/transfer/SbpFileTransferTest.java

Delete all the blobs that were transferred to SBP, using the existing
cleanup flag to disable if required.
Rename provider to match provided class.

DEV-831 Delete source files after SBP transfer

---

cluster/src/main/java/com/hartwig/pipeline/metadata/SbpSomaticMetadataApi.java
cluster/src/test/java/com/hartwig/pipeline/metadata/SbpSomaticMetadataApiTest.java
cluster/src/test/resources/sbp_api/get_run.json
cluster/src/test/resources/sbp_api/get_run_no_bucket.json

This change will ensure we always use an externally defined end bucket
for the SBP transfer, by failing if its not there.

DEV-832 Fail if no bucket defined in run

---

cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
cluster/src/main/java/com/hartwig/pipeline/cleanup/Cleanup.java
cluster/src/main/java/com/hartwig/pipeline/execution/PipelineStatus.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/healthcheck/HealthChecker.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/healthcheck/HealthCheckerTest.java

This allows us to mark a run as failed for the SBP API call without
skipping cleanups as we do on a tech failure.
Also added a status check in PipelineMain to exit 1 on tech failures
from remote jobs (vms and dataproc).

DEV-839 Add QC_FAILED status for health checker

---

cluster/src/main/java/com/hartwig/pipeline/calling/germline/GermlineCaller.java
cluster/src/main/java/com/hartwig/pipeline/calling/somatic/SomaticCaller.java
cluster/src/main/java/com/hartwig/pipeline/calling/structural/StructuralCaller.java
cluster/src/main/java/com/hartwig/pipeline/flagstat/Flagstat.java
cluster/src/main/java/com/hartwig/pipeline/metrics/BamMetrics.java
cluster/src/main/java/com/hartwig/pipeline/report/StartupScriptComponent.java
cluster/src/main/java/com/hartwig/pipeline/snpgenotype/SnpGenotype.java
cluster/src/test/java/com/hartwig/pipeline/report/StartupScriptComponentTest.java

Useful for debugging, manual re-running and auditing.
The script name is shortened when it is copied to the final output bucket.

DEV-847 Copy startup script to output bucket

---

cluster/src/main/java/com/hartwig/pipeline/Arguments.java
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/calling/germline/GermlineCaller.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/healthcheck/HealthChecker.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/purple/Purple.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/purple/PurpleApplicationCommand.java
cluster/src/test/java/com/hartwig/pipeline/calling/germline/GermlineCallerTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/healthcheck/HealthCheckerTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/purple/PurpleTest.java

Implemented as its own flag (-shallow true) as it doesn't quite fit as
a mode or profile.
When enabled will turn off germline and health check, and add some extra
args to purple for low coverage.

DEV-849 Add shallow seq config support

---

bam/src/main/java/com/hartwig/bam/ADAMKryo.java
bam/src/main/java/com/hartwig/bam/adam/FinalBAMQC.java
cluster/src/main/java/com/hartwig/pipeline/execution/dataproc/GoogleClusterConfig.java
pom.xml

Only one small thing to port, in 28 there is no longer a special fasta
datamodel, so using Sequence instead of NucleotideContigFragment.
Also using the latest dataproc image to take advantage of Spark 2.4.

DEV-852 Upgrade ADAM to 0.28

---

cluster/src/main/java/com/hartwig/pipeline/execution/MachineType.java
cluster/src/main/java/com/hartwig/pipeline/execution/dataproc/GoogleClusterConfig.java

Added disk size to the machine type to allow for different workloads to
declare a different PD disk size. Gunzip uses the default of 500, bam
creation 250 and sort and index 1000. Sort and index will likely be
removed eventually.

DEV-859 Use different disk sizes for different clusters

---

cluster/src/main/java/com/hartwig/pipeline/cleanup/Cleanup.java
cluster/src/main/java/com/hartwig/pipeline/report/FullSomaticResults.java
cluster/src/test/java/com/hartwig/pipeline/cleanup/CleanupTest.java
cluster/src/test/java/com/hartwig/pipeline/report/FullSomaticResultsTest.java

Adds an infinite retry when composing the full somatic results for both
the reference and tumor pipeline outputs. Infinite because it can be
hours later and we should detect any hanging samples elsewhere.
Also removes the deletion of the single sample staging buckets. This
will allow for reuse of the same single sample run in multiple sets,even
if the other sets have not run yet. Although we will have to find a way
to clean these up in release 5.2.

DEV-873 Wait for single sample results when staging final pipeline

---

bam/src/main/java/com/hartwig/bam/BamCreationPipeline.java
bam/src/main/java/com/hartwig/bam/adam/HDFSBamStore.java
bam/src/test/java/com/hartwig/bam/adam/HDFSBamStoreTest.java

Removes all files not suffixed with _SUCCESS or _FAILURE before starting
the bam creation.

DEV-892 Remove all files except status files before bam creation

---

cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/command/GridssCommand.java
cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/AnnotateUntemplatedSequenceTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/AnnotateVariantsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/AssembleBreakendsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/AssembleSoftClipsToSplitReadsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/CollectGridssMetricsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/ComputeSamTagsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/ExtractSvReadsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/GridssCommonArgumentsAssert.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/IdentifyVariantsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/PreProcessSoftClipsToSplitReadsTest.java
cluster/src/test/java/com/hartwig/pipeline/metrics/BamMetricsCommandTest.java

Also updated the tests as they weren't checking the GRIDSS version part of their commands.
There's an opportunity for re-use by making the test classes extend from a common ancestor but I'm not really sure how I feel about that. Comments encouraged.

DEV-865: Upgrade GRIDSS to 2.5.1

---

cluster/src/main/java/com/hartwig/pipeline/PipelineState.java
cluster/src/test/java/com/hartwig/pipeline/PipelineStateTest.java
cluster/src/test/java/com/hartwig/pipeline/SomaticPipelineTest.java

Fixes bug in which we returned a successful pipeline run, even if the
healthchecker failed. We now filter out all status not success or skip,
and whatever's left is returned as the status, or success.
Also adds a few more tests that should cover this in the future.

DEV-903 Propagate QC_FAIL to final pipeline status

---

cluster/src/main/java/com/hartwig/pipeline/RunTag.java
cluster/src/main/java/com/hartwig/pipeline/alignment/Run.java
cluster/src/main/java/com/hartwig/pipeline/cleanup/Cleanup.java
cluster/src/test/java/com/hartwig/pipeline/alignment/RunTest.java
cluster/src/test/java/com/hartwig/pipeline/cleanup/CleanupTest.java

Solves the issue of accidental reuse of shallow data by deleting the
shallow buckets even if a dependency is detected on the sample by
another run. The dependency is likely from a different sequencing.
Also appends 'shallow' to each shallow runtime resource. Not strictly
required given the above, but should make it a little easier to see on
first inspection what is running.

DEV-905 Separate shallow runtimes and always cleanup

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/ComputeEngine.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/ComputeEngineTest.java

This commit fixes a bug with the VM cleanup and zone selection logic
which would (usually) cause the run to bail when a VM already existed
from a previous run. In that situation the new run would start and
attempt to launch a new VM, but encounter an HTTP 409 because a VM
with the requested name already exists in the region.
The new zone rotation logic was passing the "previous" zone into the
cleanup code that gets called in the case of the 409, but that would
fail or succeed according to chance, because the previous zone was
regulated by the first invocation. If the wrong previous zone was used
the code would throw because it was not able to find the VM in the
expected zone.
Now the code just looks for a VM of the expected name in any of the
zones in the region and deletes it, without …

DEV-909 Fix bug with VM cleanup across runs

---

.travis.yml
cluster/Dockerfile
cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java

The current problems we're having with the bucket permissions wasn't
being seen in older builds. Try using the same version of rclone that
was in-use previously to see if it fixes the problem.

DEV-925 Pin rclone to known-working version

---

cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/BucketCompletionWatcher.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/ComputeEngine.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManager.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinition.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/BucketCompletionWatcherTest.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/ComputeEngineTest.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManagerTest.java

Refactor the ComputeEngine code to improve separation of concerns and
make it easier to fix problems. Also correct some stability issues.
Also make it so some jobs won't use pre-emptible VMs.  Regardless of
what the user requests, some VMs are better off without the
pre-emptible VMs because they run too long. For now GRIDSS is the
only one I'm adding this to.

DEV-910 Refactor compute engine code

---

cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/ResourceDownload.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinition.java
cluster/src/main/java/com/hartwig/pipeline/metadata/LocalSomaticMetadataApi.java
cluster/src/main/java/com/hartwig/pipeline/resource/ResourceNames.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/linx/Linx.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/linx/LinxCommand.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/linx/LinxOutput.java
cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
cluster/src/test/java/com/hartwig/pipeline/SomaticPipelineTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/linx/LinxTest.java
cluster/src/test/java/com/hartwig/pipeline/testsupport/TestInputs.java

Creates a new stage, linx. Linx is an HMF tool used to enrich structural
variants with annotations, interpretations and visualizations.
Linx takes purple's SV vcf (originally from gridss) as input as well as
several databases of known variants, genes, etc. In the end its a single
command.
Linx runs after the health check.

DEV-929 Add linx to pipeline

---

cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/command/AnnotateVariants.java
cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/command/AssembleBreakends.java
cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/command/CollectGridssMetrics.java
cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/command/ComputeSamTags.java
cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/command/ExtractSvReads.java
cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/command/GridssArgument.java
cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/command/IdentifyVariants.java
cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/command/SoftClipsToSplitReads.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/BashStartupScript.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/VmDirectories.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/StructuralCallerTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/AnnotateVariantsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/AssembleBreakendsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/AssembleSoftClipsToSplitReadsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/CollectGridssMetricsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/ComputeSamTagsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/ExtractSvReadsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/IdentifyVariantsTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/PreProcessSoftClipsToSplitReadsTest.java
cluster/src/test/resources/script_generation/complete_script-local_ssds
cluster/src/test/resources/script_generation/complete_script-persistent_storage

There was a bug in the structural caller that was happening
after the switch to /data/tmp for the temporary directory.
The GRIDSS commands were receiving an explicit TMP_DIR parameter
which was set to the wrong value, and which was causing the
(small) root filesystem on local-SSD-backed instances to fill
up when processing some samples.
Eliminate the explicit setting of the GRIDSS parameter and
instead export an environment variable at the top of the BASH
startup script to set the default for all JVM instances to
the desired directory.

DEV-976 Remove explicit setting of temp dir

---

cluster/src/main/java/com/hartwig/pipeline/alignment/sample/FastqNamingConvention.java
cluster/src/main/java/com/hartwig/pipeline/alignment/sample/SbpSampleReader.java
cluster/src/test/java/com/hartwig/pipeline/alignment/sample/FastqNamingConventionTest.java
cluster/src/test/java/com/hartwig/pipeline/alignment/sample/SbpSampleReaderTest.java
cluster/src/test/resources/sbp_api/get_fastq_bad_filename.json

We have a dependency on the file naming of fastq files which is a bit
hidden. If a file was to not follow the convention you'd get odd
failures (like index out of bounds).
This change adds explicit validation of the file naming and fails hard
on a clear exception if the file is unparseable.

DEV-968 Validate the fastq filename before parsing lanes

---

cluster/pom.xml
pom.xml

Also requires the addition of the jerser-hk2 module, for some sneaky
service injecting.

DEV-980 Bump jersey to jdk 11 compatible

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/OutputUpload.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/OutputUploadTest.java

My only guess is that we've hit some bug/race condition in gsutil as we
very rarely see this issue.
Trying to remove the possibility of hitting it by copying the contents
with an asterisk rather than a pure recursive copy.

DEV-999 Regig the upload copy

---

cluster/pom.xml
cluster/src/main/java/com/hartwig/pipeline/Arguments.java
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
cluster/src/main/java/com/hartwig/pipeline/alignment/AlignerProvider.java
cluster/src/main/java/com/hartwig/pipeline/metadata/SbpSomaticMetadataApi.java
cluster/src/main/java/com/hartwig/pipeline/metadata/SetMetadataApiProvider.java
cluster/src/main/java/com/hartwig/pipeline/transfer/google/GoogleArchiver.java
cluster/src/main/java/com/hartwig/pipeline/transfer/google/RetryHttpInitializerWrapper.java
cluster/src/main/java/com/hartwig/pipeline/transfer/sbp/CloudFile.java
cluster/src/main/java/com/hartwig/pipeline/transfer/sbp/ContentTypeCorrection.java
cluster/src/main/java/com/hartwig/pipeline/transfer/sbp/SbpFileTransfer.java
cluster/src/main/java/com/hartwig/pipeline/transfer/sbp/SbpFileTransferProvider.java
cluster/src/main/java/com/hartwig/pipeline/transfer/sbp/SbpS3.java
cluster/src/main/java/com/hartwig/pipeline/transfer/sbp/SbpS3FileSource.java
cluster/src/test/java/com/hartwig/pipeline/SomaticPipelineTest.java
cluster/src/test/java/com/hartwig/pipeline/metadata/SbpSomaticMetadataApiTest.java
cluster/src/test/java/com/hartwig/pipeline/smoke/ManifestAssert.java
cluster/src/test/java/com/hartwig/pipeline/smoke/SmokeTest.java
cluster/src/test/java/com/hartwig/pipeline/storage/SbpS3FileSourceTest.java
cluster/src/test/java/com/hartwig/pipeline/transfer/sbp/CloudFileTest.java
cluster/src/test/java/com/hartwig/pipeline/transfer/sbp/ContentTypeCorrectionTest.java
cluster/src/test/java/com/hartwig/pipeline/transfer/sbp/SbpFileTransferTest.java
cluster/src/test/java/com/hartwig/pipeline/transfer/sbp/SbpS3Test.java
pom.xml

Use the Google Transfer API to push the results of a run to a different
bucket in GCP for archival purposes.
As part of this, add command line arguments to allow separate credentials
to be supplied for the archive project. In production there will be a
separate project to store the archived runs.

DEV-972 Google-based archiver

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/ComputeEngine.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinition.java

As gridss was the only vm "disabled", no need for the distinction.

DEV-988 Remove pre-emptible flag from job definition

---

cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
cluster/src/main/java/com/hartwig/pipeline/SingleSamplePipeline.java
cluster/src/main/java/com/hartwig/pipeline/report/PipelineResults.java
cluster/src/test/java/com/hartwig/pipeline/SingleSamplePipelineTest.java
cluster/src/test/java/com/hartwig/pipeline/report/PipelineResultsTest.java

When a run is invoked as a simple sample "standalone" run, put the run's logs
and associated metadata at the top level of the output directory, rather than
one level further down in the sample's directory.

DEV-987 Move single sample run info to top level

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManager.java

Replace the inefficient compute.instances.list method (loop over all
VMs in all zones until the one with the required name is found) with
a more efficient direct query with the zone and instance name.

DEV-970 Make VM status check less chatty

---

cluster/src/main/java/com/hartwig/pipeline/FullPipeline.java
cluster/src/main/java/com/hartwig/pipeline/SingleSamplePipeline.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/ComputeEngine.java
cluster/src/main/java/com/hartwig/pipeline/metadata/SingleSampleEventListener.java
cluster/src/main/java/com/hartwig/pipeline/report/PipelineResults.java
cluster/src/test/java/com/hartwig/pipeline/FullPipelineTest.java
cluster/src/test/java/com/hartwig/pipeline/SingleSamplePipelineTest.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/ComputeEngineTest.java
cluster/src/test/java/com/hartwig/pipeline/report/PipelineResultsTest.java

Checks for the "UNSUPPORTED_OPERATION" error and when encountered, logs
a warning and goes to next zone. Basically the same logic as zone
resources exhausted.
Throw a runtime exception whenever a file is missing compiling the final
results.
The FullPipeline was not checking single sample state past the alignment
We know grab the final state of both single sample pipelines before
reporting the final status.

DEV-1032 Fix issues with pre-emption during vm start and error prop.

---

cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/alignment/vm/VmAligner.java
cluster/src/main/java/com/hartwig/pipeline/report/RunLogComponent.java

Add run log components for each lane alignment and the merge to the
report components. The lane logs will be in namespaced subdirectories
for each lane, as they are in the runtime bucket.

DEV-1052 Add logs to aligner

---

cluster/src/main/java/com/hartwig/pipeline/Arguments.java
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
cluster/src/main/java/com/hartwig/pipeline/metadata/SomaticMetadataApiProvider.java
cluster/src/main/java/com/hartwig/pipeline/metadata/SomaticRunMetadata.java
cluster/src/test/java/com/hartwig/pipeline/metadata/SomaticRunMetadataTest.java
cluster/src/test/java/com/hartwig/pipeline/smoke/SmokeTest.java

Make the location of metadata depend upon the contents of the API rather
than the command line arguments. Also remove the appropriate command-line
arguments which I understand should no longer be used in the field.

DEV-1074 Fix single-run metadata handling

---

cluster/src/main/java/com/hartwig/pipeline/Arguments.java
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/CommonArguments.java
cluster/src/main/java/com/hartwig/pipeline/cleanup/Cleanup.java
cluster/src/main/java/com/hartwig/pipeline/credentials/CredentialProvider.java

Makes the private key an optional argument, and if not present will use
the users own account to interact with the GCP apis. Note the service
account email is still required.
Not the cleanest use of Optional but as the credentials throw an
exception, this looks better than using map or ifpresent.

DEV-965 Use users account if no private key specified

---

batch/src/main/java/com/hartwig/batch/BatchDispatcher.java
batch/src/main/java/com/hartwig/batch/input/InputBundle.java
batch/src/main/java/com/hartwig/batch/input/InputFileDescriptor.java
cluster/src/main/java/com/hartwig/pipeline/storage/RuntimeBucket.java

Also improve the logging to include the versions as we do with the
pipeline. Further the mapping between the VM label ("number" in the
batch) and the input is now pushed to the runtime bucket at startup
so the operator can get an idea of what is going on while the run is
still happening.
The namespacing for the output has been refined so that all of the
output for a particular VM instance goes into its own directory rather
than one big directory as that does not work very well for involved
outputs.

DEV-1094 Upload dispatcher log on completion

---

batch/src/main/java/com/hartwig/batch/operations/Bam2Fastq.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/ComputeEngine.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManager.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinition.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinitionTest.java

Also decouple the disk size from the type so that whether local SSDs
or persistent storage is chosen an appropriate size will be selected
based upon the requirements of the job definition.
Also slightly amend the Bam2Fastq job to take advantage of the changes
and also hike its memory as some jobs were failing due to GC overhead
exceeding the setpoint.

DEV-1092 Allow VM to specify disk requirements

---

.travis.yml
bcl2fastq/pom.xml
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/Bcl2Fastq.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/Bcl2FastqCommand.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/Bcl2fastqArguments.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/conversion/ResultAggregation.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/metadata/FastqMetadataRegistration.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/metadata/SbpFastqMetadataApi.java
bcl2fastq/src/test/java/com/hartwig/bcl2fastq/conversion/ResultAggregationTest.java
cluster/src/main/java/com/hartwig/pipeline/Arguments.java
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/alignment/AlignerProvider.java
cluster/src/main/java/com/hartwig/pipeline/execution/MachineType.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinition.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachinePerformanceProfile.java
cluster/src/main/java/com/hartwig/pipeline/storage/GSFileSource.java
cluster/src/test/java/com/hartwig/pipeline/smoke/SmokeTest.java

Adds a toggle that once enabled, will upload fastq input from GCP rather than the SBP S3.
The location of the fastq is still taken from the SBP API (run->sample->fastq).
Also updated the Bcl2Fastq command thread settings to match production.

DEV-1101 Integrate pipeline5 with bcl2fastq on GCP

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/ComputeEngine.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/storage/PersistentStorageStrategy.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/ComputeEngineTest.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/storage/PersistentStorageStrategyTest.java

This solves the issue of the 2TB limit of the boot disk. The boot disk will
always be 100GB (although perhaps that can be reduced?) and workind disk size
the size of the new disk.
The disk is mounted in the startup script with the PersistentStorageStrategy.
this mounts /dev/sdb to /data.

DEV-1106 Always use a second PD SSD when local SSDs disabled

---

bcl2fastq/src/main/java/com/hartwig/bcl2fastq/metadata/FastqMetadataRegistration.java
bcl2fastq/src/test/java/com/hartwig/bcl2fastq/metadata/FastqMetadataRegistrationTest.java

This way we won't add additional yield or improve the Q30 average if the flowcell
fails QC.

DEV-1124 Don't update the sample if flowcell fails QC

---

bcl2fastq/src/main/java/com/hartwig/bcl2fastq/conversion/Conversion.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/conversion/ConvertedSample.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/conversion/ResultAggregation.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/metadata/FastqMetadataRegistration.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/metadata/SbpFastqMetadataApi.java
bcl2fastq/src/test/java/com/hartwig/bcl2fastq/conversion/ResultAggregationTest.java
bcl2fastq/src/test/java/com/hartwig/bcl2fastq/metadata/FastqMetadataRegistrationTest.java

Queries the fastq object after creating/updating from the conversion, and does
a calculation from the whole set rather than trying to use the state of the
current sample in the API.

DEV-1129 Use fastq objects to calculate total sample yld/q30

---

bcl2fastq/src/main/java/com/hartwig/bcl2fastq/Bcl2fastqArguments.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/OutputCopier.java
bcl2fastq/src/test/java/com/hartwig/bcl2fastq/OutputCopierTest.java

New argument to specify the email of the account which will do the output
transfer to hmf-database, and add this user as a READER to the bucket ACL.

DEV-1134 Add output service account to the ACL of runtime bucket

---

bcl2fastq/src/main/java/com/hartwig/bcl2fastq/OutputCopier.java
bcl2fastq/src/test/java/com/hartwig/bcl2fastq/OutputCopierTest.java

The transfer account also needs storage.objects.get on each file.

DEV-1134 Add to ACL on individual files as well

---

bcl2fastq/src/main/java/com/hartwig/bcl2fastq/OutputCopier.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/conversion/ConvertedFastq.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/conversion/ResultAggregation.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/metadata/FastqMetadataRegistration.java
bcl2fastq/src/test/java/com/hartwig/bcl2fastq/OutputCopierTest.java
bcl2fastq/src/test/java/com/hartwig/bcl2fastq/conversion/ResultAggregationTest.java

In production trials we've seen conversions with only the R1 values. By making
the R2 optional we can support this permutation of input.

DEV-1140 Make all the R2 fields optional

---

bcl2fastq/src/main/java/com/hartwig/bcl2fastq/conversion/Conversion.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/conversion/ConvertedUndetermined.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/conversion/ResultAggregation.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/metadata/FastqMetadataRegistration.java
bcl2fastq/src/main/java/com/hartwig/bcl2fastq/stats/UndeterminedStats.java
bcl2fastq/src/test/java/com/hartwig/bcl2fastq/OutputCopierTest.java
bcl2fastq/src/test/java/com/hartwig/bcl2fastq/conversion/ResultAggregationTest.java
bcl2fastq/src/test/java/com/hartwig/bcl2fastq/metadata/FastqMetadataRegistrationTest.java

A bit of a refactor to make things more consistent. We create an object in our Conversion datamodel to hold
the undetermined stats. This is populated from read metrics now deserialized in the UndeterminedStats
All stats in Conversion are now derived, to ensure the numbers are always consistent across the datamodel.

DEV-1142 Include undetermined yield in Q30 calculations

---

bcl2fastq/src/main/java/com/hartwig/bcl2fastq/Bcl2fastqArguments.java
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/storage/RuntimeBucket.java
cluster/src/test/java/com/hartwig/pipeline/storage/RuntimeBucketTest.java

While the argument class supported it, we didn't actually have it wired in as
a CLI arg. Also removing the defaulting of the location and project of the key
to allow for use of keys in other projects.

Enable CMEK for BCL conversion

---

cluster/src/main/java/com/hartwig/pipeline/FullPipeline.java
cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
cluster/src/main/java/com/hartwig/pipeline/PipelineState.java
cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
cluster/src/main/java/com/hartwig/pipeline/StageOutput.java
cluster/src/main/java/com/hartwig/pipeline/cram/CramConversion.java
cluster/src/main/java/com/hartwig/pipeline/metadata/AddDatatypeToFile.java
cluster/src/main/java/com/hartwig/pipeline/metadata/AdditionalApiCalls.java
cluster/src/main/java/com/hartwig/pipeline/metadata/ApiFileOperation.java
cluster/src/main/java/com/hartwig/pipeline/metadata/LinkFileToSample.java
cluster/src/main/java/com/hartwig/pipeline/metadata/LocalSomaticMetadataApi.java
cluster/src/main/java/com/hartwig/pipeline/metadata/SbpSomaticMetadataApi.java
cluster/src/main/java/com/hartwig/pipeline/metadata/SomaticMetadataApi.java
cluster/src/main/java/com/hartwig/pipeline/sbpapi/AddFileApiResponse.java
cluster/src/main/java/com/hartwig/pipeline/sbpapi/FileResponse.java
cluster/src/main/java/com/hartwig/pipeline/sbpapi/SbpRestApi.java
cluster/src/main/java/com/hartwig/pipeline/transfer/SbpFileApiUpdate.java
cluster/src/test/java/com/hartwig/pipeline/FullPipelineTest.java
cluster/src/test/java/com/hartwig/pipeline/PipelineStateTest.java
cluster/src/test/java/com/hartwig/pipeline/SomaticPipelineTest.java
cluster/src/test/java/com/hartwig/pipeline/metadata/SbpSomaticMetadataApiTest.java
cluster/src/test/java/com/hartwig/pipeline/report/PipelineResultsTest.java
cluster/src/test/java/com/hartwig/pipeline/transfer/SbpFileApiUpdateTest.java

Allow calling of arbitrary API endpoints after files have been created
so that we can add additional metadata for certain files from the run.

DEV-1250 Register CRAMs with API

---

cluster/src/main/java/com/hartwig/pipeline/SingleSamplePipeline.java
cluster/src/main/java/com/hartwig/pipeline/metadata/AddDatatypeToFile.java
cluster/src/main/java/com/hartwig/pipeline/metadata/LinkFileToSample.java
cluster/src/main/java/com/hartwig/pipeline/report/PipelineResults.java
cluster/src/main/java/com/hartwig/pipeline/transfer/SbpFileApiUpdate.java
cluster/src/test/java/com/hartwig/pipeline/SingleSamplePipelineTest.java
cluster/src/test/java/com/hartwig/pipeline/report/PipelineResultsTest.java

We encountered a failure in production in which a failure in the CRAM
stage resulted in a rerun of the pipeline, but after the rerun succeeded
the output directory did not contain the files from the sample that had
failed the first time (none of them; the subdirectory for the sample
itself wasn't even present).
Looks like the reason for this was that the flag file which tells the
pipeline that the staging directory has been populated was left-over
from the first run, which meant that upon re-run the pipeline didn't
wait for the files to be copied from the staging bucket into the final
archive bucket.
Also improve logging output for post-applied operations to make
debugging this problem easier.

DEV-1279 Copy all single-pipeline files on rerun

---

cluster/src/main/java/com/hartwig/pipeline/calling/somatic/SageV2Caller.java
cluster/src/test/java/com/hartwig/pipeline/calling/germline/GermlineCallerTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/somatic/SageV2CallerTest.java
cluster/src/test/java/com/hartwig/pipeline/stages/StageTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/bachelor/BachelorTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/chord/ChordTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/healthcheck/HealthCheckerTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/linx/LinxTest.java

Currently the output is not used in the shallow run and it doesn't provide anything interesting to use later. Disable the caller when the shallow flag is true.  Also added a more general test in StageTest for shallow mode. This way the subclasses can declare whether they are enabled for shallow with a simple boolean override.

DEV-1287 Disable sage caller when shallow run 

---

cluster/src/main/java/com/hartwig/patient/Lane.java
cluster/src/main/java/com/hartwig/pipeline/alignment/sample/FastqFiles.java
cluster/src/main/java/com/hartwig/pipeline/alignment/sample/SbpSampleReader.java
cluster/src/main/java/com/hartwig/pipeline/alignment/vm/LaneAlignment.java
cluster/src/main/java/com/hartwig/pipeline/alignment/vm/RecordGroupId.java
cluster/src/main/java/com/hartwig/pipeline/alignment/vm/VmAligner.java
cluster/src/test/java/com/hartwig/pipeline/alignment/sample/SbpSampleReaderTest.java
cluster/src/test/java/com/hartwig/pipeline/alignment/vm/LaneAlignmentTest.java
cluster/src/test/java/com/hartwig/pipeline/alignment/vm/Lanes.java
cluster/src/test/java/com/hartwig/pipeline/alignment/vm/RecordGroupIdTest.java
cluster/src/test/java/com/hartwig/pipeline/alignment/vm/VmAlignerTest.java
cluster/src/test/java/com/hartwig/pipeline/storage/CloudSampleUploadTest.java

Simplifies the record group id parsing by using the fastq file path as input, rather than
the lane which is parsed from the API or json. This also results in the removal of a couple
of those ill defined field in the lane, suffix, index and name.

DEV-1289 Use fastq file directly rather than lane parsing for RG

---

pom.xml

This is an official version with CRAM support. Up until now we've been
using a local advance version as an official version had been delayed.
Also move this dependency to the test scope, we no longer need it in the
main app.

DEV-1372 Update to official HTSJDK version

---

cluster/src/main/java/com/hartwig/pipeline/PipelineState.java
cluster/src/main/java/com/hartwig/pipeline/SingleSamplePipeline.java
cluster/src/main/java/com/hartwig/pipeline/transfer/SbpFileApiUpdate.java
cluster/src/test/java/com/hartwig/pipeline/SingleSamplePipelineTest.java

Not precisely sure yet why sometimes multiple copies of the
same operation are requested but it is not incorrect to store
and apply the operations in a set rather than a list. 
This will resolve the problem we are currently seeing 
anyway.

DEV-1386 Link to datatype/sample once per file

---

cluster/src/main/java/com/hartwig/pipeline/report/PipelineResultsProvider.java

If the pipeline creates this bucket (as it is likely to do when we are
running Platinum) it will now check that a CMEK is specified and apply
it to the new bucket.

DEV-1420 Apply CMEK to patient report bucket

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/ComputeEngine.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManager.java
cluster/src/main/java/com/hartwig/pipeline/failsafe/DefaultBackoffPolicy.java
cluster/src/main/java/com/hartwig/pipeline/stages/StageRunner.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/ComputeEngineTest.java
cluster/src/test/java/com/hartwig/pipeline/failsafe/DefaultBackoffPolicyTest.java

Now all interactions in the Lifecycle manager are retried with a backoff.

DEV-1428 Wrap all list operations in a backoff retry

---

cluster/src/main/java/com/hartwig/pipeline/sbpapi/SbpRestApi.java

Remove extra functions to submit json, post and patch. Each had its own way
of checking status.

Refactor duplication out of api

---

cluster/src/main/java/com/hartwig/patient/ReferenceTumorPair.java
cluster/src/main/java/com/hartwig/pipeline/alignment/sample/JsonSampleSource.java
cluster/src/main/java/com/hartwig/pipeline/metadata/LocalSomaticMetadata.java
cluster/src/test/java/com/hartwig/pipeline/metadata/LocalSomaticMetadataTest.java
sample_json/cancerPanelSingleSample.json

By making it optional, we can carry that forward to the metadata construction and leverage the
existing logic to kick into single sample mode.

DEV-1530 Make tumor optional in JSON

---

.travis.yml
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/CommonArguments.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/GoogleComputeEngine.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/GoogleComputeEngineTest.java
cluster/src/test/java/com/hartwig/pipeline/smoke/SmokeTest.java

Subnet is optional, and if not specified the old behaviour of using the same name as the
network is used (and the region for everything else). Tags are added to the instance when
specified.

DEV-1575 Add command line options for subnet and network tags

---

cluster/src/main/java/com/hartwig/pipeline/SingleSamplePipeline.java
cluster/src/main/java/com/hartwig/pipeline/cram/CramConversion.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinition.java
cluster/src/test/java/com/hartwig/pipeline/cram/CramConversionTest.java

There was a failure in production because of disk space limitations on
an unusually-large tumor sample.
Also since the initial writing of the pipeline I believe GCP relaxed
their requirement that SSDs be provisioned in pairs, so I've also
removed the code that bumped that up if the calculated value was odd.
As a consequence of this, I have also upped the default for disk space
from 900MB to 1200MB as very few jobs specify a non-default
number for the disk space. Previously, 900MB would be calculated to 3
disks but rounded up to 4 and I don't know what the jobs that don't
specify an explicit value, actually need.

DEV-1707 Increase disk for tumor CRAM conversions

---

cluster/src/main/java/com/hartwig/pipeline/alignment/bwa/BwaAligner.java
cluster/src/main/java/com/hartwig/pipeline/calling/germline/GermlineCaller.java
cluster/src/main/java/com/hartwig/pipeline/calling/sage/SageCaller.java
cluster/src/main/java/com/hartwig/pipeline/calling/structural/StructuralCaller.java
cluster/src/main/java/com/hartwig/pipeline/calling/structural/StructuralCallerPostProcess.java
cluster/src/main/java/com/hartwig/pipeline/cram/CramConversion.java
cluster/src/main/java/com/hartwig/pipeline/metadata/AddDatatype.java
cluster/src/main/java/com/hartwig/pipeline/metadata/ArchivePath.java
cluster/src/main/java/com/hartwig/pipeline/metrics/BamMetrics.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/amber/Amber.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/bachelor/Bachelor.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/chord/Chord.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/cobalt/Cobalt.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/linx/Linx.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/purple/Purple.java
cluster/src/test/java/com/hartwig/pipeline/cram/CramConversionTest.java
cluster/src/test/java/com/hartwig/pipeline/metadata/AddDatatypeTest.java
cluster/src/test/java/com/hartwig/pipeline/metadata/ArchivePathTest.java
cluster/src/test/java/com/hartwig/pipeline/metrics/BamMetricsTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/amber/AmberTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/bachelor/BachelorTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/chord/ChordTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/cobalt/CobaltTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/linx/LinxTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/purple/PurpleTest.java
cluster/src/test/java/com/hartwig/pipeline/transfer/SbpFileApiUpdateTest.java

Extracted the path creation logic into a simple path class to remove some duplication and make it
a little clearer what AddDatatype accepts.
Otherwise linx we use the first of the tsvs in alphabetical order, and bachelor we use the germline
variant tsv as that is where the "main" data resides.

DEV-1786 All add datatypes use a path to an actual file

---

cluster/src/main/java/com/hartwig/pipeline/resource/RefGenome38ResourceFiles.java

The resources now contain a VCF so that the pipeline run will finish
if done under HG38. That VCF is currently a husk with no actual data in
it so the subsequent patient DB load will not actually put anything into
the database, however this will be resolved when a proper VCF for 38 is
available.

DEV-1798 Support HG38 Amber PON after all

---

cluster/src/main/java/com/hartwig/pipeline/PipelineState.java
cluster/src/test/java/com/hartwig/pipeline/PipelineStateTest.java

Rather than trying to imply it in one stream operation.

DEV-1876 Explicitly check for QC_FAIL and FAIL

---

cluster/src/main/java/com/hartwig/pipeline/SingleSamplePipeline.java
cluster/src/main/java/com/hartwig/pipeline/alignment/AlignmentOutput.java
cluster/src/main/java/com/hartwig/pipeline/cram/CramConversion.java
cluster/src/main/java/com/hartwig/pipeline/cram2bam/Cram2Bam.java
cluster/src/main/java/com/hartwig/pipeline/datatypes/FileTypes.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/GoogleComputeEngine.java
cluster/src/main/java/com/hartwig/pipeline/reruns/StartingPoint.java
cluster/src/test/java/com/hartwig/pipeline/SingleSamplePipelineTest.java
cluster/src/test/java/com/hartwig/pipeline/cram2bam/Cram2BamTest.java

Adds an optional stage between the aligner and other tools which will convert any alignment with the
extension .cram back to .bam and use that downstream.

DEV-1881 Convert crams to bams if used for downstream algos

---

cluster/images/base.cmds

The base commands have been amended to just copy everything from the
bucket after the git repo is fetched from. The `-n` flag has been
provided to `gsutil` in order to prevent it overwriting anything that
was already cloned from the repository. In that situation a warning
is issued by `gsutil` which should be good enough.
Further a few more commands were added to un-gzip some of the new
resources which were stored un-compressed in the bucket but compress
well and have been compressed in the repository. It is worth keeping
the repository as small as possible for usability and maintenance
reasons so this seems a good trade-off. Also many of the text-based
resources are already stored compressed so it's not a big departure.

DEV-1941 Rework handling of repo/bucket resources

---

cluster/src/main/java/com/hartwig/pipeline/metadata/ResearchMetadataApi.java
cluster/src/main/java/com/hartwig/pipeline/metadata/SomaticMetadataApiProvider.java
cluster/src/main/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisher.java
cluster/src/test/java/com/hartwig/pipeline/metadata/ResearchMetadataApiTest.java
cluster/src/test/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisherTest.java
pom.xml

Depending on the context. The clinical API publishes the "patient report" target and the research api
publishes the "database" target.

DEV-1965 Publish output target with stage events

---

cluster/src/main/java/com/hartwig/pipeline/Arguments.java
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/metadata/Anonymizer.java
cluster/src/main/java/com/hartwig/pipeline/metadata/ClinicalSomaticMetadataApi.java
cluster/src/main/java/com/hartwig/pipeline/metadata/ResearchMetadataApi.java
cluster/src/main/java/com/hartwig/pipeline/metadata/SomaticMetadataApiProvider.java
cluster/src/test/java/com/hartwig/pipeline/metadata/AnonymizerTest.java
cluster/src/test/java/com/hartwig/pipeline/metadata/ClinicalSomaticMetadataApiTest.java
cluster/src/test/java/com/hartwig/pipeline/metadata/ResearchMetadataApiTest.java

Introduces a simple class which takes a sample and produces an "anonymized" name, which now is
simply the barcode. Applied in both clinical and research api implementations.

DEV-1966 Add option to anonymize with barcodes

---

cluster/src/main/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisher.java
cluster/src/test/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisherTest.java

Shallow analysis will be removed from the event api. Shallow pipelines will only publish
patient report outputs, so will not be picked up for archival.

DEV-1947 Remove publishing of shallow events

---

cluster/src/main/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisher.java

Otherwise we fail on single sample runs.

DEV-1974 Fallback on reference sample when publishing staged event

---

cluster/src/main/java/com/hartwig/pipeline/alignment/AlignerProvider.java

Bit of an interim fix for this to minimize impact, but removes references to the rclone and
s3 sample uploading from the production alignment.

DEV-2022 Wire in GS based upload classes to "SBP" providers

---

cluster/src/main/java/com/hartwig/pipeline/transfer/staged/InNamespace.java
cluster/src/main/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisher.java
cluster/src/test/java/com/hartwig/pipeline/transfer/staged/InNamespaceTest.java
cluster/src/test/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisherTest.java

And add the new namespaces for the secondary analysis. The idea being that these are extensions of the
secondary analysis (metrics and metadata).

DEV-2024 Use namespaces over filenames to differentiate analysis types

---

cluster/src/main/java/com/hartwig/pipeline/metadata/AddDatatype.java
cluster/src/main/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisher.java
cluster/src/test/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisherTest.java

If its not present, we leave the barcode empty (we only need barcode when mapping samples with datatype).

DEV-2048 Use the barcode from the AddDatatype object

---

cluster/src/main/java/com/hartwig/pipeline/metrics/BamMetrics.java
cluster/src/test/java/com/hartwig/pipeline/metrics/BamMetricsTest.java

This will be picked up by the StagedOutputPublisher even though the stage has not actually been run. Then the archiver
will receive the datatype and barcode and add the proper file api links.
As bam metrics are the only non-cram files grouped into the secondary staged event, we only pull this trick in one place.
Longer term it would be good to factor the code such that persisted results always honor the datatype of the normal
output generation.
Test plan:
- Run research pipeline in pilot
- Ensure that the file is persisted with api objects
- Run DB loader and check that MetricsLoader is run.

DEV-2082 Add datatype to the persisted output of bam metrics

---

cluster/src/main/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisher.java
cluster/src/test/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisherTest.java

Add the sage germline namespace and then look for all files with germline in the name. Bit of a dirty trick
but at this point we don't have another option unless we inventory every file we archive.

DEV-2121 Ensure all germline data ends up the germline analysis bucket

---

cluster/src/main/java/com/hartwig/pipeline/metadata/ResearchMetadataApi.java
cluster/src/test/java/com/hartwig/pipeline/metadata/ResearchMetadataApiTest.java

The research api implementation is used in reruns, to this point didn't populate the DOID on the
tumor sample.

DEV-2186 Populate DOIDs in research metadata api

---

cluster/images/create_public_image.sh
cluster/images/mk_python_venv
cluster/images/tools.cmds
cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java

There were a few problems here: (1) Another PR for PEACH was created
uner this same branch name to update one of the dependencies, as the
existing version had stopped building properly.
(2) Potentially frustrating things with the dependencies was the fact that
the `pip` command was not being properly propagated into the PyEnv
environments unless the copy that we extract from our tarball into
`/root/.pyenv` was first updated. The symptom was that the `pip` command
would be namespaced under Python version 3.5 instead of 3.6 in the
virtual environment, which if nothing else was confusing.
(3) I've added some cleanup commands in the `tools.cmds` to delete existing
PyEnv and tools as problems are caused by having the Python environments
already in place when running with the `-t` command.
Also …

DEV-2217 Fix up problems with imager

---

cluster/images/installDependencies.R.cran40

This file is not yet used but when we are ready to move to Debian 10
from the already-deprecated Debian 9 for the pipeline we'll need to
rebuild the R libraries.
R libraries are coupled to the environment they were compiled in and our
current production version uses cran35 while the new one uses cran40.

DEV-2197 R dependencies for Debian 10

---

cluster/src/main/java/com/hartwig/pipeline/tertiary/peach/Peach.java
cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/peach/PeachTest.java

This is required to properly fix the problems we were having with resolving
Python dependencies as this version updates one of those which was no longer
installable.
Also sometime between the previous 1.0 version and this one the format of the
command line changed so that has been updated too.

DEV-2221 Upgrade PEACH to v1.3

---

batch-operations/src/main/java/com/hartwig/batch/operations/LilacBatch.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/peach/Peach.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/peach/PeachTest.java

Remove the disused vctools argument and update the name of the version argument
to tool_version.
Separately to this the resources were also updated and a new image made.

DEV-2221 Update PEACH arguments

---

batch-operations/src/main/java/com/hartwig/batch/operations/TeloBatch.java
batch/src/main/java/com/hartwig/batch/BatchDispatcher.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/InputDownload.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/QuotaConstrainedComputeEngine.java

The symptoms of the problem were that the "finished" counter in the batches
was incrementing rather quickly but this did not appear to be tied to actual VM
lifecycles.
Turns out this was due to failing to consider the API in the creation of the
VM configuration. The inputs were being resolved against the dataset but the
traffic on the API was too much and it was falling over.
I've introduced retry mechanisms on the API communication and also am now
properly handling failures such that exceptions outside
of the ComputeEngine are now rippled back up to the status reporter as
pipeline failures.
Also correct typo I happened across and commit the tunings I did to the
TeloBatch.

DEV-2296 Fix intermittent failure in batch

---

cluster/src/main/java/com/hartwig/pipeline/metadata/ApiRunStatus.java
cluster/src/main/java/com/hartwig/pipeline/metadata/DiagnosticSomaticMetadataApi.java
cluster/src/main/java/com/hartwig/pipeline/metadata/ResearchMetadataApi.java
cluster/src/main/java/com/hartwig/pipeline/metadata/SomaticMetadataApiProvider.java
cluster/src/test/java/com/hartwig/pipeline/metadata/DiagnosticSomaticMetadataApiTest.java
cluster/src/test/java/com/hartwig/pipeline/metadata/ResearchMetadataApiTest.java

Diagnostics already populated the status, so extracted that code to be shared between the apis and added
the time population to them.  Using a standard ISO format for date (UTC)

DEV-2227 Populate start and end time on both diag and research runs

---

batch/src/main/java/com/hartwig/batch/BatchArguments.java
cluster/src/main/java/com/hartwig/pipeline/execution/MachineType.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinition.java

The batch framework currently makes it a bit too easy to create expensive
runs. This change removes the ability to use non-pre-emptible VMs, as the cost
difference is a factor of 5x.
Also change the default for VM definitions to a custom machine with 8 cores
and 8GB RAM. The references in the rest of the pipeline code have been updated
to use custom machines reflecting the original default.

DEV-2303 Make batch defaults safer

---

cluster/Dockerfile
cluster/images/base.cmds
cluster/src/main/java/com/hartwig/pipeline/execution/vm/InputDownloadIfBlobExists.java
cluster/src/main/java/com/hartwig/pipeline/resource/ResourceFiles.java
cluster/src/main/java/com/hartwig/pipeline/resource/ResourceNames.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/cuppa/Cuppa.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/orange/Orange.java
cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/cuppa/CuppaTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/orange/OrangeTest.java
cluster/src/test/java/com/hartwig/pipeline/testsupport/TestInputs.java

Version bump plus a couple new resources.
Also implemented a fix here to check for the existence in GCS of the feature plot. This enables use
of the Orange 1.2 feature to pass a non-existent cuppa feature plot as an argument (the feature plot
is not always used).

DEV-2358 Orange upgrade to 1.4

---

cluster/images/create_private_image.sh

There was an underscore in the name of the private image, which isn't
allowed under the naming rules for GCP images.
Also there was what appears to be a timing issue with the `git` checkout
from the private image VM, which was failing repeatedly from multiple
machines for us today. A simple `sleep 60` seems to have at least
allowed a single operation to succeed so let's wait and see whether that
lasts.

DEV-2382 Fix some bugs in the private imager

---

cluster/src/main/java/com/hartwig/pipeline/alignment/bwa/BwaAligner.java

Download the FASTA file specified by the 'reference_genome_url'
command line option and the associated index files
to the VM's used for FASTQ alignment.

DEV-2394 Download overridden reference FASTA to alignment VM's

---

cluster/images/tools.cmds
cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/stage/Driver.java
cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/stage/RepeatMasker.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/virus/VirusBreakendCommand.java
cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
cluster/src/test/java/com/hartwig/pipeline/calling/sage/SageCommandBuilderTest.java
cluster/src/test/java/com/hartwig/pipeline/calling/structural/StructuralCallerTest.java
cluster/src/test/java/com/hartwig/pipeline/cram/CramConversionTest.java
cluster/src/test/java/com/hartwig/pipeline/cram2bam/Cram2BamTest.java
cluster/src/test/java/com/hartwig/pipeline/metrics/BamMetricsCommandTest.java
cluster/src/test/java/com/hartwig/pipeline/metrics/BamMetricsTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/virus/VirusAnalysisTest.java

Version bump plus samtools upgrade to 1.14 and removal of sh
suffix from all gridss script invocations.

DEV-2523 Upgrade GRIDSS to 2.13.2

---

cluster/images/create_public_image.sh
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/CommonArguments.java
cluster/src/main/java/com/hartwig/pipeline/resource/OverridePanelCommand.java
cluster/src/main/java/com/hartwig/pipeline/resource/PanelEnabled.java
cluster/src/main/java/com/hartwig/pipeline/resource/RefGenome37ResourceFiles.java
cluster/src/main/java/com/hartwig/pipeline/resource/ResourceFiles.java
cluster/src/main/java/com/hartwig/pipeline/resource/ResourceFilesFactory.java
cluster/src/main/java/com/hartwig/pipeline/resource/ResourceNames.java
cluster/src/main/java/com/hartwig/pipeline/stages/StageRunner.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/HmfToolCommandBuilder.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/amber/Amber.java
cluster/src/test/java/com/hartwig/pipeline/resource/OverridePanelCommandTest.java
cluster/src/test/java/com/hartwig/pipeline/resource/PanelEnabledTest.java

The panel bed is configured as an optional arg and can be either a location within the
image or a location in google cloud storage
The bed is integrated with the resource files in a similar manner to the reference genome
where the GCS based bed is auto-downloaded by the stage runner prior to stage start.
Stages can then decide whether to use the panel bed via ResourceFiles

DEV-2573 Add panel bed to common resources

---

cloudbuild.yaml
cluster/pom.xml
pom.xml

The release profile no longer creates a docker container, but still creates the runnable
jar and copies the dependencies to the correct locations for the containerization. So we
call it release and not "smoke test".

DEV-2634 Disable "release" (aka docker) profile by default

---

cluster/src/main/java/com/hartwig/pipeline/calling/sage/SageCaller.java
cluster/src/main/java/com/hartwig/pipeline/calling/sage/SageCommandBuilder.java
cluster/src/main/java/com/hartwig/pipeline/calling/sage/SageConfiguration.java
cluster/src/main/java/com/hartwig/pipeline/calling/sage/SageGermlineCaller.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/pave/PaveGermline.java

Fixes several places where the tumor sample is referenced by in reference only mode.
Remove check in sage command builder making tumor mandatory

DEV-2593 Fix incorrect references to tumor in reference-only

---

cluster/images/create_pilot_image.sh

Really a small change just to make sure that there is a pilot image
family. The original changes to add the pilot imaging capability were
done so that there is little chance of a pilot version getting beyond
the development environment.
However this change makes it easier for multiple devs to work at the
same time without trampling one another. While we've always had the
situation where multiple imagers working at the same time will trample
one another, it's never really been an issue. However the pilot workflow
and the "regular" dev workflow are distinct so it's better to keep them
separate.
This change puts the onus on the developer to make sure they're setting
the image in their run's arguments for the pilot flow.

DEV-2686 Write pilot images to separate family

---

cluster/images/create_private_image.sh
cluster/images/private_resource_checkout.sh

The imager will be invoked with the extra parameters added here to allow us to build an automated workflow to ease CKB updates.
Argument parsing has been rewritten for `private_resource_checkout.sh` as the new functionality requires us to be able to request a particular commit of the resources be used for imaging, while the typical development flow is looser and just always uses `HEAD`. Also in the development flow we generate a new tag to automatically apply to the resources repository while in the automated flow we want to use a particular commit of the resources and _not_ tag anything.
Changes to `create_private_image.sh` are minor and just support the changes to the other script.

DEV-2705 Imager changes to support regular CKB updates

---

cluster/images/create_private_image.sh
cluster/images/private_resource_checkout.sh

This change for the private imager continues to support the existing
mode of operation, but adds support for a new flow in which instead of
using SSH to poll for activity, the script waits for the presence of the
given path in a bucket.
With this change we can support launching the imager from within a
Docker container launched by the Cloud Build environment and not having
to fiddle with creating and propagating SSH keys to the VM instance
doing the imaging.
When the script is provided a bucket URL argument, it switches into the
new bucket-based mode. In that case instead of copying the private
resource checkout script to the imager instance after it starts and
waiting for it to complete, the script will set the startup script
metadata of the instance to the local file. Also instead of …

DEV-2705 Support bucket-based completion detection

---

cluster/images/create_private_image.sh
cluster/images/create_public_image.sh
cluster/images/private_resource_checkout.sh

This makes our development process more robust by allowing multiple developers
to work in parallel on tickets that amend the resources, and also protects the
production image from changes that haven't been explicitly merged to `master`.
When a branch is used for the public image, a distinct family will also be used
and no tag will be written to the repository so that image won't be available
to use as the base for a private image.
I've also amended the private imaging script to allow passing any "target"
instead of just a SHA on the command line; the user can now use a tag, commit
SHA or branch. When run from within GCP though only a SHA will be supported.
Options in the public script have switched to long-only to match the private
script's behaviour.

DEV-2793 Allow using branch for public resources

---

cluster/images/create_pilot_image.sh
cluster/images/link_pilot_venvs.sh

We create Python virtualenvs in their own directories for several of our
tools. However when we try to run these tools with a pilot version,
there is no virtualenv with a name matching the version and so it can't
be found at runtime.
I've added a script to locate the virtualenv for the latest version of
the tool (with some limitations) and this should be enough to get us
working in 99% of cases. Actually I expect this will only ever really be
an issue with Cuppa but it's possible we add tools later in a similar
vein.

DEV-2798 Python venv support for pilot images

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/GoogleComputeEngine.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinition.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/amber/Amber.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/GoogleComputeEngineTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/amber/AmberTest.java

Removing the termination action entirely to allow for manual deletion of vms without
the pipeline restarting them.
Amber settings reduced as per Charles/Hongs recommendations and using a slightly
smaller thread count than available CPU to reduce saturation of VM.

DEV-2832 Remove termination action for local ssd/reduce amber footprint

---

cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
cluster/src/main/java/com/hartwig/pipeline/reruns/StartingPoint.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/lilac/Lilac.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/lilac/LilacTest.java

And the required tests. rerun_530 starting point is updated to not run the
slicer for now.

DEV-2835 Add persisted output to lilac

---

cluster/src/main/java/com/hartwig/pipeline/resource/ResourceFiles.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/rose/Rose.java
cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/rose/RoseTest.java

Upgrade to ROSE v1.1. Note the use of some temporary/dummy arguments as the new version requires them but the report will still generate fine without "real" data.

DEV-2831 Update arguments for ROSE

---

cluster/images/check_deps.sh
cluster/images/create_private_image.sh
cluster/images/create_public_image.sh
cluster/images/private_resource_checkout.sh

This may be an anaemic check but it is better than what we had. On MacOS
the default getopt implementation is based on the BSD version and
doesn't support long options.
When invoked with "-V", the default version on modern Linux
installations (from the GNU foundation) returns a version, while the
MacOS version just returns "--". I've used this to create a simple
suitability check and we now print a warning with details for MacOS
users.

DEV-2853 Check for correct getopt before running

---

cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/CommonArguments.java
cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java

This enables us to specify where events get published so we can have multiple
pipeline runs in the same GCP project; previously we relied on the event type
only to determine the topic to which events would be published.

DEV-2845 Optional topic workflow argument

---

cluster/src/main/java/com/hartwig/pipeline/alignment/AlignerProvider.java
cluster/src/main/java/com/hartwig/pipeline/alignment/persisted/PersistedAlignment.java
cluster/src/test/java/com/hartwig/pipeline/alignment/persisted/PersistedAlignmentTest.java

When use cram is false, and we start from alignment complete, and no API dataset is available, we first try to locate the bams and then the crams.

DEV-2959 Default to cram when bam not present

---

cluster/src/main/java/com/hartwig/pipeline/Arguments.java
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
cluster/src/main/java/com/hartwig/pipeline/alignment/AlignerProvider.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/GoogleComputeEngine.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/NoOpComputeEngine.java
cluster/src/main/java/com/hartwig/pipeline/report/PipelineResults.java
cluster/src/main/java/com/hartwig/pipeline/report/PipelineResultsProvider.java
cluster/src/test/java/com/hartwig/pipeline/calling/sage/SageCommandBuilderTest.java
cluster/src/test/java/com/hartwig/pipeline/report/PipelineResultsTest.java

This will allow us to escape from the current situation in which the events for the 5.30 rerun have expired leaving us with no way to archive them now that they have been verified.
By invoking the pipeline with the new argument set we should incur little cost and also be more-confident of the correct outcome than if we were for instance trying to construct the datasets out of the data in the output bucket.
Also fix the `SageCommandBuilderTest` which appears to have been broken since the last commit to the hotfix branch.
I don't love the name of the argument but want to get across that it's not purely a "no op" since it does publish events, but it's also doing none of the heavy lifting that a full pipeline run does. Suggestions welcome.

DEV-2974 Add "publish events only" mode/argument

---

cluster/src/main/java/com/hartwig/pipeline/Arguments.java
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java

In the interests of eliminating friction for Platinum after we've rolled out 5.31, change as little as possible in the argument handling.
However currently we use defaults for the private key if it is not specified; we don't want to do that anymore as it will interfere with the delegation to defaults when run in GCP.

DEV-2873 Make keys optional, remove defaults

---

cluster/src/main/java/com/hartwig/pipeline/failsafe/DefaultBackoffPolicy.java

We have witnessed this exception multiple times in production but it does not reproduce easily. Because we retry forever when there is any issue this bug threatens the stability and turnaround characteristics of the pipeline, since once it has been encountered once in a given invocation it will never succeed. We have also seen it in the batch framework.
The current handling mechanism just prints out the message from any exception; I have decided to abort when this specific exception is encountered and instead of retrying print the full stack trace. If nothing else maybe we will get hints on what is happening so we can address the root cause. This will also ensure the pipeline doesn't sit forever but instead the rest of our framework will restart the job.
In my testing this approach …

DEV-2991 Handle GCP InvalidArgumentException

---

cluster/src/main/java/com/hartwig/pipeline/calling/germline/GermlineCaller.java
cluster/src/main/java/com/hartwig/pipeline/reruns/StartingPoint.java

Remove germline caller from the skipped stages in alignment complete starting point.
Don't run the germline caller if the context is not research.

DEV-3035 Run germline caller for research runs

---

cluster/src/main/java/com/hartwig/pipeline/alignment/bwa/BwaAligner.java
cluster/src/test/java/com/hartwig/pipeline/alignment/bwa/BwaAlignerTest.java

I think this was a side-effect of the PDL conversion. Without this change there is no user project set on the inputs, so for instance cram2bam will not be able to fetch the CRAMs to do its work.

DEV-3142 Add billing project for alignment output

---

cluster/src/main/java/com/hartwig/pipeline/Arguments.java
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/RunTag.java
cluster/src/main/java/com/hartwig/pipeline/input/MetadataProvider.java
cluster/src/test/java/com/hartwig/pipeline/CommandLineOptionsTest.java
cluster/src/test/java/com/hartwig/pipeline/smoke/SmokeTest.java
pom.xml

Prefer the PDL set name to the command-line argument. Also rename the command line option as `set_id` is confusing, it's a name.
I think I must be missing something here, seems like there should be more references to this parameter.

DEV-3144 Pull in set name from PDL

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/BashStartupScript.java
cluster/src/test/resources/script_generation/complete_script-local_ssds
cluster/src/test/resources/script_generation/complete_script-persistent_storage

I've tested this and it appears to work correctly but there may be some corner cases.
Just shut down the VM when it finishes doing its work. We never ended up using the exit code on-VM so replace the "exit" command with it in the "die" block.

DEV-3146 Shutdown at end of startup script

---

cluster/src/main/java/com/hartwig/pipeline/FullPipeline.java
cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
cluster/src/main/java/com/hartwig/pipeline/metadata/HmfApiStatusUpdate.java
cluster/src/test/java/com/hartwig/pipeline/FullPipelineTest.java
cluster/src/test/java/com/hartwig/pipeline/metadata/HmfApiStatusUpdateTest.java

This necessitated a refactor as the "finish" update for the API could no longer
be in the top-level `PipelineMain` class and some of the data required was not
being passed further down into the `FullPipeline` instance.

DEV-3153 Reorder event publishing and API update

---

cluster/src/main/java/com/hartwig/pipeline/tertiary/protect/Protect.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/rose/Rose.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/protect/ProtectTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/rose/RoseTest.java

These are out of date and for now it's easiest just to disable them.
I believe the smoke test will continue to function with no further changes and the unit tests also pass. We will likely be removing them soon anyway.

DEV-3163 Disable ROSE and PROTECT for research

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManager.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManagerTest.java

We have had several signficant cost overruns in production recently due to endless retries of GCP operations. This is most certainly due to a bug in the code changed in this commit.

DEV-3178 Eliminate endless looping on GCP ops

---

cluster/src/main/java/com/hartwig/pipeline/input/MetadataProvider.java
cluster/src/test/java/com/hartwig/pipeline/input/MetadataProviderTest.java

The sample name was being set on the barcode field in the generated metadata, correct this and add a test.

DEV-3183 Set barcode correctly in metadata

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/GoogleComputeEngine.java
cluster/src/main/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManager.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/GoogleComputeEngineTest.java
cluster/src/test/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManagerTest.java

I have removed the messy loop that previously composed much of the executeSynchronously() method, replacing it with the mechanism recommended in Google's documentation for waiting on a running operation.
Logging of any errors in the InstanceLifecycleManager now occurs at the ERROR level, though most exceptions will be thrown back up to the StageRunner where the stage itself will be retried. This is somewhat of a middle ground; it can only result in more production alerts but should help us get a handle on which operations actually routinely fail, while also properly handling any errors that do come up.
There is more work to do here but I am reluctant to do too much as this is such a core piece of our infrastructure. I will revisit at some point in the future, when this release has been …

DEV-3178 Further simplify VM management

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinition.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/purple/Purple.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/purple/PurpleTest.java

There is currently a run in the research environment that is failing on a Java OutOfMemoryError. 31GB worked in the diagnostic run which is using an older Purple version.

DEV-3227 Increase Purple memory

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManager.java

The deletion code was incorrect because it located an old instance but then tried to delete that from the zone the new instance was going to be placed into. This would work sometimes (as there are only 3 zones in europe-west4) but not always.
With the recent change to the logging it is now obvious what was happening.

DEV-3234 Fix bug in old instance deletion

---

cluster/src/main/java/com/hartwig/pipeline/Arguments.java

In actin infra we don't want to use cmek. The default of empty does not function, it should really be Optional.empty.

ACTIN-88 Remove erroneous "empty" cmek

---

cluster/src/main/java/com/hartwig/pipeline/reruns/StartingPoint.java

We recently disabled the germline caller in research, moving it to diagnostic. The research launcher copies the germline output along with the alignment output from the diagnostic output bucket as it always did. However since the germline stage is skipped in the research run, we don't mark the output for that stage with any datatypes. Using this new starting point will result in the datatypes for the germline being applied which should correct the problem.
A corresponding change will need to be made in the launcher code and this will fix the problem for forthcoming runs. There are some runs that have already been archived that will not be fixed, I will craft an SQL file to update the API file entries for these as the only thing missing is the datatypes (ie the archiver otherwise ran …

DEV-3243 Add temporary research starting point

---

cluster/src/main/java/com/hartwig/pipeline/input/MetadataProvider.java
cluster/src/test/java/com/hartwig/pipeline/input/MetadataProviderTest.java

When the barcode is NA use the sample name. This is a minimal fix for 5.32, longer term we should make barcode an optional field in PDL and then handle without the string comparison in the pipeline.

DEV-3247 Fallback to sample name if barcode is "NA"

---

cluster/images/create_private_image.sh

Since we already have a confirmation the user must agree with before we will continue it doesn't really reduce the security of this script to allow non-HEAD locations to be requested without an additional prompt. The confirmation is easily defeated anyway; it's just a guard against mistakes.

DEV-3315 Add "official" flag to private imager

---

cluster/src/main/java/com/hartwig/pipeline/tertiary/orange/Orange.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/orange/OrangeTest.java

These files are used only by ACTIN currently and that project doesn't need the datatypes at the moment. Without this change we end up with a list of items under the key in the dataset which breaks existing clients.

DEV-3541 Don't add datatypes to germline Orange

---

cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java

This was done in 5.32 but didn't get propagated to 5.33.
When this has been approved it will also be merged to master.

DEV-3676 Bump Purple heap to 31G

---

cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
cluster/src/main/java/com/hartwig/pipeline/input/MetadataProvider.java
cluster/src/main/java/com/hartwig/pipeline/input/SingleSampleRunMetadata.java
cluster/src/test/java/com/hartwig/pipeline/alignment/RunTest.java
cluster/src/test/java/com/hartwig/pipeline/alignment/bwa/BwaAlignerTest.java
cluster/src/test/java/com/hartwig/pipeline/input/MetadataProviderTest.java
cluster/src/test/java/com/hartwig/pipeline/storage/CloudSampleUploadTest.java
cluster/src/test/java/com/hartwig/pipeline/testsupport/TestInputs.java
cluster/src/test/resources/pipeline-input/with_dataset.json
cluster/src/test/resources/smoke_test/reference/samples.json
cluster/src/test/resources/smoke_test/tumor-reference/samples.json
cluster/src/test/resources/smoke_test/tumor/samples.json
pom.xml

This change uses a new field from PDL `turquoiseSubject` to pass on to turquoise via the event. This allows pipeline5 to publish turquoise events using a different subject/name than what is used to generate output files.

DEV-3682 Publish turquoise subject in turquoise

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManager.java

The changes that resulted in adding the retries have been battle-tested in production and I'm confident we've got a correct implementation so we can avoid alerting on it every time now.

DEV-3483 Demote retried operation logging to warn

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinition.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/cuppa/Cuppa.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/lilac/Lilac.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/peach/Peach.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/sigs/Sigs.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/virus/VirusInterpreter.java
cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java

The `HmfTool` class and the VM definitions both define parameters for the VMs that our in-house tooling runs on. I noticed this while trying to increase the memory for Purple and when it wasn't working realised the situation.
Reference the HmfTool-hosted constants from within the VM definition calls whenever they exist as not doing this violates the principle of least surprise. Also I think the intent of the HmfTool class must have been to centralise the configuration as much as possible and this is a step in that direction.
I am aware this is an imperfect solution as the constants don't exist for those tools we don't maintain and a couple of the tools use different parameters depending on which "mode" they've been called in, Sage springs to mind.
I checked pretty thoroughly for …

DEV-3688 Unify VM core and memory declarations

---

cluster/src/main/java/com/hartwig/pipeline/tertiary/orange/Orange.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/orange/OrangeTest.java

Orange can't be given a plot dir arg when the folder is missing. Just create it for now.

DEV-3706: quick fix to missing linx plot

---

cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
cluster/src/main/java/com/hartwig/pipeline/input/SingleSampleRunMetadata.java
cluster/src/main/java/com/hartwig/pipeline/turquoise/Event.java
cluster/src/main/java/com/hartwig/pipeline/turquoise/Label.java
cluster/src/main/java/com/hartwig/pipeline/turquoise/PublishingTurquoise.java
cluster/src/main/java/com/hartwig/pipeline/turquoise/Subject.java
cluster/src/main/java/com/hartwig/pipeline/turquoise/Turquoise.java
cluster/src/test/java/com/hartwig/pipeline/alignment/bwa/BwaAlignerTest.java
cluster/src/test/java/com/hartwig/pipeline/turquoise/PublishingTurquoiseTest.java
cluster/src/test/java/com/hartwig/pipeline/turquoise/TurquoiseTest.java
pom.xml

Behaviour will be to throw an exception if Turquoise is enabled and no subject. Otherwise subject can be empty when turquoise is disabled.
Small refactor to encapsulate this logic.

ACTIN-444 Support turquoise subject as an optional input

---

cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
cluster/src/main/java/com/hartwig/pipeline/turquoise/PublishingTurquoise.java
cluster/src/main/java/com/hartwig/pipeline/turquoise/Turquoise.java

The `Turqouise` interface is used for publishing certain pubsub messages through a pubsub publisher. However, currently `Turqouise` implementations do not properly shutdown the publisher after using it, resulting in the following stacktrace: 
```log
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=1, target=pubsub.googleapis.com:443} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
```
This PR addresses this:
- Make the `Turquoise` interface extend `AutoClosable`.
- Implement the `close` method in all implementaitons by calling `shutdown` on the publisher.
- Add missing `@Override` annotations, following best practices.

INFRA-119 fix Turqoise pubsub bug

---

.mvn/extensions.xml
cloudbuild.yaml
cluster/src/test/java/com/hartwig/pipeline/smoke/SmokeTest.java
pom.xml

- Update cloud build to use `docker-tag` and `$TAG_NAME`.
- Add mvn `extension.xml` file to ensure ide support for downloading sources and documentation.
- Change deployment location to artifact registry.

DEV-3490 update release method

---

cloudbuild.yaml
cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java

Only update is PAVE version (was 1.5.0, becomes 1.5.1).
Also needed to update the cloudbuild to work with new (tag based) setup.

DEV-3721 PAVE hotfix

---

pom.xml

Uptick to `hmf-cloud-sdk` 3.0.3 which no longer uses the `QuotaConstrainedComputeEngine`. In turn this should get rid of the `DEADLINE_EXCEEDED` warnings once and for all.

INFRA-242 get rid of quota constrained compute engine and DEADLINE_EXCEEDED warnings

---

cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/orange/Orange.java
cluster/src/test/java/com/hartwig/pipeline/stages/StageTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/cuppa/CuppaTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/orange/OrangeTest.java

I have tried to make sure that all combinations of targeted vs WGS and tumor-only vs tumor-and-ref do something useful without crashing.
For tumor-only runs, Orange-no-germline is still disabled, since the result would be basically the same as the "regular" Orange run.

DEV-3758: Enable Orange for targeted tumor-only runs

---

cluster/images/create_public_image.sh
cluster/images/tools.cmds
cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java
sample_json/coloMini.json

Changes:
- Germline resources update (see [this commit in common public resources repo](https://source.cloud.google.com/hmf-pipeline-development/common-resources-public/+/857361bd316e68249ea18fb24f9b4bf61853a280))
- Orange update to `2.6.2` (enabling the use of added germline reporting)
- PURPLE hotfix to `3.9.4` (fixing a small issue that allowed LOW_TUMOR_VCN to be reportable)

INFRA-152 germline reportability hotfix 533

---

README.md
cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java
cluster/src/main/java/com/hartwig/pipeline/tools/VersionUtils.java

The latest commit of this branch (5.35.0-beta.1) has been tested using pipeline image `pipeline5-5-35-202403061046`
COLO has been run and compared with 5.34.1 using compar, results in gs://hmf-crunch-experiments/240308_kd_verification_pipeline_v5_35_0, differences have been deemed acceptable.

ACTIN-688: Upgrade various tools in pipeline

---

cluster/src/main/java/com/hartwig/pipeline/Arguments.java
cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/cuppa/Cuppa.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/cuppa/CuppaTest.java

Makes it possible for pipeline5 to run in both a public mode (using a public compute image without the private CUPPA resource file) and private mode (using a private compute image with the private CUPPA resource file)
For this I added argiment `use_private_resources`. The only downside is that to actually use the private resource file (cuppa_cv_predictions.37.tsv.gz) the argument must be provided, but this makes the intention also very clear and explicit so worth the trade-off.
Previous code tried to detect the existance of the file but that did not work since that check was executed in the k8 job instead of on the CUPPA stage VM.

INFRA-326 Allow usage of Cuppa private resource file

---

pom.xml

Use a new hmf-cloud-sdk with a bugfix for the polling interval. The value provided with poll_interval argument should now no longer be ignored.

INFRA-345 Fix polling interval

---

cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java

This is where we had it before the HMF markdup implementation.

ACTIN-786 Bump markdups memory

---

cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java

Teal does not need to hold the whole pipeline execution hostage because its output is not used anywhere. On the run I was watching, Teal ran for exactly 1 hour which is significant.
I also moved Lilac down to just above the "final" block of quick- running tools at the end since it too was running synchronously.

ACTIN-809 Reorder stage management statements

---

cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java
image/create_public_image.sh

Also revise imaging script behaviour to print out a message with details on where the script was generated to, rather than require the user to copy/paste commands to get it to run.

ACTIN-818 Bump MarkDups to 1.1.4

---

cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
cluster/src/main/java/com/hartwig/pipeline/tools/VersionUtils.java
image/create_public_image.sh
image/private_resource_checkout.sh
image/tools.cmds

Probably not super-exciting, much of this is just restoring some stuff that disappeared from `master` sometime in February I think it was.
Once the changes were restored I decided to update the list of JARs that is coming from Artifact Registry too, when I first made these changes only Orange was in there but now we've got a decent-sized list. Think it would be worthwhile to continue this process and eventually mostly eliminate the `hmftools` bucket from the flow for HMF-maintained tooling.

ACTIN-835 Fix minor recent Pv5 merge mistakes + use AR

---

cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java

A hotfixed CUPPA is already added to 5.34 by Luan, this commit also updates Orange and TEAL and increases the memory for CIDER a bit.

INFRA-396 534 various tool bugfixes

---

cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java

Intended for a 5.34.6 pipeline release.

DEV-4026: Update MarkDups and increase memory and max heap

---

cluster/src/main/java/com/hartwig/pipeline/failsafe/DefaultBackoffPolicy.java

This is to fix a problem where gcp request failure just prints a `Bad request` with no reason given.

INFRA-469: when a gcp request has failed, print the causes

---

cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinitions.java
cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java

Gave Lilac VM more RAM and heap. Reduced core count of lane alignment VM.

DEV-4026: Prevent some out of memory crashes

---

cluster/src/main/java/com/hartwig/pipeline/resource/ResourceFiles.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/orange/Orange.java
cluster/src/main/java/com/hartwig/pipeline/tertiary/virus/VirusInterpreter.java
cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java
cluster/src/main/java/com/hartwig/pipeline/tools/VersionUtils.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/orange/OrangeTest.java
cluster/src/test/java/com/hartwig/pipeline/tertiary/virus/VirusInterpreterTest.java

Confirmed the md5s of the Github JARs match those in the `common-tools` bucket.
Image will be `pipeline5-5-37-202407251032-202407251112-private`.

ACTIN-1134 Orange > 3.7.0, virusint > 1.5.0

---

cloudbuild-pr.yaml
cluster/src/main/java/com/hartwig/pipeline/snpgenotype/SnpGenotype.java
cluster/src/test/java/com/hartwig/pipeline/smoke/SmokeTest.java
cluster/src/test/resources/log4j.xml
pom.xml

This change makes sure that for Targeted mode (which runs on HG38 in our production setup) also output the `snp_genotype.vcf` file with 26 or 31 SNP genotype calls. This will allow performing of snpcheck once the MIP-based snpcheck is ready for production.
Tested this change by running on TARGETED COLO from `gs://hmf-verification-data-fastq/COLO829-TARGETED/` and comparing the resulting snp genotype VCF with the same file from WGS COLO, which yielded a perfect match for all 26 positions.

INFRA-696 Run SnpGenotype in HG38 mode

---

cluster/src/main/java/com/hartwig/pipeline/resource/RefGenome37ResourceFiles.java
cluster/src/main/java/com/hartwig/pipeline/resource/RefGenome38ResourceFiles.java
cluster/src/main/java/com/hartwig/pipeline/resource/ResourceFiles.java
cluster/src/main/java/com/hartwig/pipeline/snpgenotype/SnpGenotype.java
cluster/src/test/java/com/hartwig/pipeline/snpgenotype/SnpGenotypeTest.java
cluster/src/test/resources/smoke_test/reference/expected_output_files
cluster/src/test/resources/smoke_test/tumor-reference/expected_output_files
cluster/src/test/resources/smoke_test/tumor/expected_output_files

Same change that was merged into 5.33 and 5.34 hotfix branches.
- `mvn clean test` yields BUILD SUCCESS
- COLO mini hg37 from BAM runs fine with image `pipeline5-6-0-202409241531`

INFRA-786 Add 31SNP output to genotype stage

---

cloudbuild-pr.yaml
cloudbuild.yaml
cluster/Dockerfile

The tag-based build was still using the Docker image that was accidentally deleted as its base. 
Also update the Docker image used from 1.7.4-beta.6 to 1.7.5.

DEV-4111: Update Docker images in Cloud Build

---

cluster/src/main/java/com/hartwig/pipeline/output/PipelineCompleteEventPublisher.java
pom.xml

Needed to locate the right pipeline in the pipeline reference data, which will replace the lists of analyses blobs. Keep the analyses blobs for now to remain backwards compatible.

INFRA-938 Include more metadata in pipeline.complete event

---

cluster/src/main/java/com/hartwig/pipeline/alignment/redux/Redux.java

The code erroneously swapped the files `jitter_params.tsv.gz` and `ms_table.tsv.gz` in the alignment output.

INFRA-1104 Fix Redux output files jitter_params and ms_table
