- cluster/src/test/java/com/hartwig/pipeline/io/sbp/SbpS3Test.java
> DEV-888 Using expected over catching the exception in test

- cluster/src/main/java/com/hartwig/pipeline/calling/structural/StructuralCaller.java
- cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/command/ExtractSvReads.java
- cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/stage/CommandFactory.java
- cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/stage/Preprocess.java
- cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/ExtractSvReadsTest.java
- cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/stage/PreprocessTest.java
Pass the working directory in through pre-process to ensure we use the
same working dir everywhere
> DEV-826 Put sv metrics output of extract sv reads into working dir

- .travis.yml
Which will run a simple mvn clean install or add the -DskipDocker on a
PR build
> DEV-836 Override travis maven script with conditional

- .travis.yml
- system/pom.xml
Turn off shading with -DskipShade
> DEV-837 Put shading behind a profile and skip during PR builds

- cluster/images/standard.cmds
- cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/command/RscriptFilter.java
- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/calling/structural/gridss/command/RscriptFilterTest.java
Also merge GRIDSS scripts into the same tools directory as the
GRIDSS JAR since the versions for the scripts are essentially
arbitrary anyway and we can't do much without the scripts.
> DEV-897 Update GRIDSS scripts

- cluster/images/installDependencies.R
- cluster/images/standard.cmds
- cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
- cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinition.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/chord/Chord.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/chord/ChordExtractSigPredictHRD.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/chord/ChordOutput.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/linx/Linx.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/purple/Purple.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/purple/PurpleOutput.java
- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/SomaticPipelineTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/chord/ChordTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/linx/LinxTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/purple/PurpleTest.java
- cluster/src/test/java/com/hartwig/pipeline/testsupport/TestInputs.java
Chord is an R based tool used to predict HRD. It takes the somatic and
structural variants from purple as input.
> DEV-863 Add Chord to pipeline

- cluster/src/main/java/com/hartwig/pipeline/calling/somatic/SomaticCaller.java
- cluster/src/test/java/com/hartwig/pipeline/smoke/LocalOverrides.java
- cluster/src/test/java/com/hartwig/pipeline/smoke/SmokeTest.java
- cluster/src/test/resources/smoke_test/expected_output_files
Also make it so environment overrides can be specified to make it
so the smoke test can be run locally without much work.
> DEV-1008 Add SAGE hotspot files to output

- cluster/src/test/java/com/hartwig/pipeline/smoke/LocalOverrides.java
Didn't turn out to be much. Just use immutables to reduce boilerplate.
> DEV-1014 Fix up smoke test overrides

- batch/src/main/java/com/hartwig/batch/operations/Bam2Fastq.java
- cluster/images/pipeline5.cmds
- cluster/src/main/java/com/hartwig/pipeline/alignment/vm/SambambaMarkdupCommand.java
- cluster/src/main/java/com/hartwig/pipeline/alignment/vm/SambambaSortCommand.java
- cluster/src/main/java/com/hartwig/pipeline/alignment/vm/SambambaViewCommand.java
- cluster/src/main/java/com/hartwig/pipeline/calling/command/VersionedToolCommand.java
- cluster/src/main/java/com/hartwig/pipeline/execution/vm/SambambaCommand.java
- cluster/src/main/java/com/hartwig/pipeline/execution/vm/VirtualMachineJobDefinition.java
Job for running bulk bam2fastq.
> DEV-1070 Batch version of bam2fastq

- cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
- cluster/src/main/java/com/hartwig/pipeline/calling/somatic/SomaticCaller.java
> DEV-1098 Update hotspot file for SAGE

- bcl2fastq/src/main/java/com/hartwig/bcl2fastq/metadata/FastqMetadataRegistration.java
- bcl2fastq/src/main/java/com/hartwig/bcl2fastq/metadata/SbpSample.java
- bcl2fastq/src/test/java/com/hartwig/bcl2fastq/metadata/FastqMetadataRegistrationTest.java
> DEV-1128 Update sample name along with yld and q30

- .travis.yml
- cluster/src/main/java/com/hartwig/pipeline/calling/structural/StructuralCaller.java
- cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/command/RscriptFilter.java
- cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/stage/Driver.java
- cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/stage/Filter.java
- cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/stage/TabixDriverOutput.java
- cluster/src/test/java/com/hartwig/pipeline/calling/structural/StructuralCallerTest.java
- cluster/src/test/java/com/hartwig/pipeline/testsupport/AlignmentFileAssertion.java
- cluster/src/test/resources/smoke_test/expected_output_files
3 files will be persisted:
gridss.unfiltered: All somatic and germline variants
gridss.somatic: All somatic variants
gridss.somatic.filtered: All somatic variant passing quality standards
> DEV-1132 Persist correct gridss outputs

- bcl2fastq/src/main/java/com/hartwig/bcl2fastq/conversion/ResultAggregation.java
- bcl2fastq/src/main/java/com/hartwig/bcl2fastq/metadata/FastqMetadataRegistration.java
- bcl2fastq/src/main/java/com/hartwig/bcl2fastq/metadata/SbpFlowcell.java
- bcl2fastq/src/test/java/com/hartwig/bcl2fastq/conversion/ResultAggregationTest.java
Also correct spelling issue in undet_rds field for SBP API update.
> DEV-1138 Sum undetermined yield with fastq yield to get total

- batch/src/main/java/com/hartwig/batch/BatchArguments.java
- bcl2fastq/src/main/java/com/hartwig/bcl2fastq/Bcl2fastqArguments.java
- cluster/src/main/java/com/hartwig/pipeline/CommonArguments.java
Just a matter of adding the args, which will be picked up by ComputeEngine. Also pulled up constants into CommonArguments to share
the code.
> DEV-1162 Adds arguments for bcl2fastq and batch for private networking

- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/purple/PurpleTest.java
> DEV-1293 Upgrade purple to 2.43

- cluster/src/main/java/com/hartwig/pipeline/execution/vm/ComputeEngine.java
- cluster/src/test/java/com/hartwig/pipeline/execution/vm/ComputeEngineTest.java
Takes advantage of the logic already present for zone exhaustion.
> DEV-1406 Retry on quota exceeded

- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/bachelor/BachelorTest.java
> DEV-1509 Upgrade bachelor to 1.12

- cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
- cluster/src/test/resources/smoke_test/rclone.conf
INFO when success, ERROR when not.
> DEV-1515 Add a completion message summarizing the run

- cluster/src/main/java/com/hartwig/pipeline/metadata/SbpSomaticMetadataApi.java
- cluster/src/main/java/com/hartwig/pipeline/metadata/SingleSampleRunMetadata.java
- cluster/src/main/java/com/hartwig/pipeline/sbpapi/SbpSample.java
- cluster/src/test/java/com/hartwig/pipeline/metadata/SbpSomaticMetadataApiTest.java
- cluster/src/test/resources/sbp_api/get_samples_by_set.json
It will then be serialized into the metadata.json
> DEV-1590 Include doids in single sample metadata

- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/purple/PurpleTest.java
> DEV-1940 Upgrade to PURPLE 2.54

- cluster/src/main/java/com/hartwig/pipeline/tertiary/linx/Linx.java
- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/linx/LinxTest.java
Also remove unreferenced constant from Linx class
> DEV-1962 Bump Linx version to 1.15

- ivdr/release-notes-5.22.md
- ivdr/release-notes-template.md
Template provided from the IVDR requirements, we add our own sections for features and bug
fixes.
> DEV-1949 Add IVDR template and example for 5.22

- cluster/src/main/java/com/hartwig/pipeline/Arguments.java
- cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
- cluster/src/main/java/com/hartwig/pipeline/metadata/DiagnosticSomaticMetadataApi.java
- cluster/src/main/java/com/hartwig/pipeline/metadata/SomaticMetadataApiProvider.java
- cluster/src/main/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisher.java
- cluster/src/test/java/com/hartwig/pipeline/metadata/DiagnosticSomaticMetadataApiTest.java
- cluster/src/test/java/com/hartwig/pipeline/metadata/ResearchMetadataApiTest.java
- cluster/src/test/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisherTest.java
- pom.xml
Also add an argument to allow us to specify the analysis context.
> DEV-2019 Update to events 1.2

- cluster/images/tools.cmds
These take a long time to compile.
> DEV-2109 Install rather than compile Perl deps

- cluster/images/tools.cmds
- cluster/src/main/java/com/hartwig/pipeline/tertiary/cuppa/Cuppa.java
- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/cuppa/CuppaTest.java
Simple version bump along with the required python extraction and venv creation in the
image.
> DEV-2341 Cuppa 1.5

- cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/virus/VirusAnalysis.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/virus/VirusInterpreter.java
- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/SomaticPipelineTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/virus/VirusAnalysisTest.java
Use the new version and wire in the purple QC and purity TSV along with the tumor
wgs metrics. Virus analysis moves down the pipeline until just after purple.
> DEV-2244 VirusInterpreter 1.1

- cluster/src/main/java/com/hartwig/pipeline/resource/ResourceFiles.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/virus/VirusAnalysis.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/virus/VirusInterpreter.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/virus/VirusAnalysisTest.java
Replace the blacklist and interpretation TSV with the new reporting db TSV
> DEV-2322 Adjust arguments to virus interpreter 1.1

- cluster/src/main/java/com/hartwig/pipeline/Arguments.java
- cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
- cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
- cluster/src/main/java/com/hartwig/pipeline/metadata/SomaticMetadataApiProvider.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/healthcheck/HealthChecker.java
- cluster/src/main/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisher.java
- cluster/src/test/java/com/hartwig/pipeline/metadata/ResearchMetadataApiTest.java
- cluster/src/test/java/com/hartwig/pipeline/smoke/SmokeTest.java
- cluster/src/test/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisherTest.java
- pom.xml
Combines the 3 events into a single event composed of 3 analyses.
> DEV-2347 Integrating the new events API

- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/orange/OrangeTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/protect/ProtectTest.java
Also fix Orange test that was failing for me.
> DEV-2511 Bump Protect version to 2.0

- cluster/src/main/java/com/hartwig/pipeline/Arguments.java
- cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
- cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
- cluster/src/main/java/com/hartwig/pipeline/calling/sage/SageCaller.java
- cluster/src/main/java/com/hartwig/pipeline/calling/sage/SageCommandBuilder.java
- cluster/src/main/java/com/hartwig/pipeline/calling/sage/SageConfiguration.java
- cluster/src/main/java/com/hartwig/pipeline/reruns/StartingPoint.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/purple/Purple.java
- cluster/src/main/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisher.java
- cluster/src/test/java/com/hartwig/pipeline/SomaticPipelineTest.java
- cluster/src/test/java/com/hartwig/pipeline/calling/sage/SageCommandBuilderTest.java
- cluster/src/test/java/com/hartwig/pipeline/calling/sage/SageGermlineCallerTest.java
- cluster/src/test/java/com/hartwig/pipeline/calling/sage/SageSomaticCallerTest.java
- cluster/src/test/java/com/hartwig/pipeline/reruns/StartingPointTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/purple/PurpleTest.java
- cluster/src/test/java/com/hartwig/pipeline/testsupport/TestInputs.java
Finish of the last spike/wip PR.
> DEV-2546 Complete refactoring of SAGE

- cluster/src/main/java/com/hartwig/pipeline/Arguments.java
- cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
- cluster/src/main/java/com/hartwig/pipeline/calling/structural/gridss/Gridss.java
- cluster/src/main/java/com/hartwig/pipeline/calling/structural/gripss/Gripss.java
- cluster/src/test/java/com/hartwig/pipeline/calling/structural/GridssTest.java
- cluster/src/test/java/com/hartwig/pipeline/calling/structural/GripssGermlineTest.java
- cluster/src/test/java/com/hartwig/pipeline/calling/structural/GripssSomaticTest.java
Will simplify the launcher configuration.
> DEV-2613 Remove caller specific toggles from arguments

- cluster/pom.xml
- cluster/src/main/java/com/hartwig/pipeline/credentials/CredentialProvider.java
- cluster/src/main/java/com/hartwig/pipeline/execution/vm/GoogleComputeEngine.java
- cluster/src/main/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManager.java
- cluster/src/test/java/com/hartwig/pipeline/execution/vm/GoogleComputeEngineTest.java
- cluster/src/test/java/com/hartwig/pipeline/execution/vm/InstanceLifecycleManagerTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/orange/OrangeTest.java
- pom.xml
To call this API needed to upgrade to the lastest version of the
compute API. Lots of changes but all good, builders and removal
of annoying "execute" methods.
> DEV-2805 Create VMs with provision mode SPOT

- cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/lilac/LilacBamSlicer.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/virus/VirusInterpreter.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/lilac/LilacBamSlicerTest.java
Also I will be looking through the other stages to audit them for similar problems.
> DEV-2830 Fix bug in LilacBamSlicer persisted output

- cluster/src/main/java/com/hartwig/pipeline/calling/sage/SageCaller.java
- cluster/src/main/java/com/hartwig/pipeline/calling/structural/gripss/Gripss.java
- cluster/src/main/java/com/hartwig/pipeline/cram/CramConversion.java
- cluster/src/main/java/com/hartwig/pipeline/flagstat/Flagstat.java
- cluster/src/main/java/com/hartwig/pipeline/metrics/BamMetrics.java
- cluster/src/main/java/com/hartwig/pipeline/stages/Stage.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/amber/Amber.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/chord/Chord.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/cobalt/Cobalt.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/cuppa/Cuppa.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/cuppa/CuppaOutput.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/cuppa/CuppaOutputLocations.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/healthcheck/HealthChecker.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/lilac/Lilac.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/lilac/LilacBamSlicer.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/linx/LinxGermline.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/linx/LinxSomatic.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/orange/Orange.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/pave/Pave.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/peach/Peach.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/protect/Protect.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/purple/Purple.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/rose/Rose.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/sigs/Sigs.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/virus/VirusBreakend.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/virus/VirusInterpreter.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/TertiaryStageTest.java
- cluster/src/test/java/com/hartwig/pipeline/testsupport/TestInputs.java
I've added this to the interface and also modified the implementors (with a few
exceptions) to override it and call it from both the output() and
persistedOutput() methdos.
> DEV-2836 Augment stage with addDatatypes method

- .run/Tumor Reference COLO mini.run.xml
- cluster/src/main/java/com/hartwig/patient/Sample.java
- cluster/src/main/java/com/hartwig/pipeline/metadata/AddDatatype.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/amber/Amber.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/cobalt/Cobalt.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/linx/LinxSomatic.java
- cluster/src/main/java/com/hartwig/pipeline/transfer/staged/OutputDataset.java
- cluster/src/main/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisher.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/cobalt/CobaltTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/linx/LinxSomaticTest.java
- cluster/src/test/java/com/hartwig/pipeline/transfer/staged/OutputDatasetTest.java
Adds all datatypes to a map to produce a compatible Dataset.java. The dataset is
serialized to json and uploaded to the output bucket.
> DEV-2844 Serialize a dataset to json at end of run

- cluster/src/main/java/com/hartwig/pipeline/resource/ResourceFiles.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/rose/Rose.java
- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/rose/RoseTest.java
Upgrade rose, remove the primary tumors arg and use the cup results CSV over the conclusions txt.
> DEV-2929 Rose 1.3

- cluster/pom.xml
- cluster/src/main/java/com/hartwig/pipeline/Arguments.java
- cluster/src/main/java/com/hartwig/pipeline/CommandLineOptions.java
- cluster/src/main/java/com/hartwig/pipeline/CommonArguments.java
- cluster/src/main/java/com/hartwig/pipeline/PipelineMain.java
- cluster/src/main/java/com/hartwig/pipeline/metadata/LocalSomaticMetadata.java
- cluster/src/main/java/com/hartwig/pipeline/metadata/SomaticMetadataApiProvider.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/healthcheck/HealthChecker.java
- cluster/src/main/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisher.java
- cluster/src/test/java/com/hartwig/pipeline/metadata/LocalSomaticMetadataTest.java
- cluster/src/test/java/com/hartwig/pipeline/metadata/ResearchMetadataApiTest.java
- cluster/src/test/java/com/hartwig/pipeline/smoke/SmokeTest.java
- cluster/src/test/java/com/hartwig/pipeline/transfer/staged/StagedOutputPublisherTest.java
- pom.xml
Package renaming and refactoring to use the new EventPublisher.
Switch to artifact repository for the events dependency.
> DEV-2988 Port pipeline to new events api and module

- cluster/images/create_public_image.sh
- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
We have not done this in the past but I think as more people join the project now is a good time.
> DEV-3145 Remove version duplication

- cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/orange/Orange.java
- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/orange/OrangeTest.java
Version bump and add the disclaimer when RUO.
> DEV-3237 Upgrade orange to 2.4

- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/chord/ChordTest.java
Version bump, chord only (not sig extractor)
> DEV-3237 Upgrade chord 2.02

- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/linx/LinxGermlineTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/linx/LinxSomaticTest.java
Fix for issue with empty germline SV input
> DEV-3260 Upgrade linx to 1.23.6

- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/smoke/SmokeTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/linx/LinxGermlineTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/linx/LinxSomaticTest.java
The set name is now stored in the PDL, so we should adjust where the
smoke test looks for the output.
> ACTIN-99 Fix smoke test

- cluster/images/create_private_image.sh
These two work in the same way, make the terms consistent. The feature allows the user to specify a `git` target (commit, tag, branch, etc), not just a commit as the previous terminology in the private imager may have led a user to believe.
> DEV-3279 Make private imager match public terms

- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/pave/PaveGermlineTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/pave/PaveSomaticTest.java
> DEV-3286 Increment Pave version

- cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/pave/PaveGermlineTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/pave/PaveSomaticTest.java
Corrects a bug in certain samples that causes a stage failure.
> DEV-3313 Bump PAVE to 1.4.5

- cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java
It feels too easy to me so please check if I haven't omitted a step somewhere!
> ACTIN-288: Bump ORANGE to v2.7.0

- cluster/src/main/java/com/hartwig/pipeline/output/PipelineCompleteEventPublisher.java
- cluster/src/test/java/com/hartwig/pipeline/output/PipelineCompleteEventPublisherTest.java
Ironically the output for this stage was going into the _germline_ archive bucket. While there are no files registered to the output the data requests do grant access to the buckets these files live in.
> DEV-3568 Fix bucket allocation for non-GL Orange

- README.md
- image/README.md
Some changes to the CI section in the main README.md.
Updates to the image README.md to add information on the "typical" case in which the script is used.
> ACTIN-806 Update READMEs w/quickstart, new procs

- cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java
- cluster/src/main/java/com/hartwig/pipeline/tools/VersionUtils.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/orange/OrangeTest.java
- image/README.md
- image/create_public_image.sh
- image/tools.cmds
Note: I didn't manage to make a new pipeline image, which means default build failed and haven't tested on COLO829
> ACTIN-1003: Upgrade various tools in pipeline

- cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java
> DEV-4077: Update Orange from 3.3.1 to 3.3.2

- cluster/src/main/java/com/hartwig/pipeline/resource/RefGenome37ResourceFiles.java
- cluster/src/main/java/com/hartwig/pipeline/resource/RefGenome38ResourceFiles.java
- cluster/src/main/java/com/hartwig/pipeline/resource/ResourceFiles.java
- cluster/src/main/java/com/hartwig/pipeline/snpgenotype/SnpGenotype.java
- cluster/src/test/java/com/hartwig/pipeline/snpgenotype/SnpGenotypeTest.java
- cluster/src/test/resources/smoke_test/reference/expected_output_files
- cluster/src/test/resources/smoke_test/tumor-reference/expected_output_files
- cluster/src/test/resources/smoke_test/tumor-reference/truthset/lilac/COLO829v003T.lilac.qc.tsv
- cluster/src/test/resources/smoke_test/tumor/expected_output_files
- sample_json/coloMiniFromBam.json
Also added a sample json to run COLO mini from BAM to speed up testing (when running pipeline5 from Intellij).
> INFRA-786 Add 31SNP genotype output for MIP-based snpcheck

- cluster/src/main/java/com/hartwig/pipeline/resource/RefGenome37ResourceFiles.java
- cluster/src/main/java/com/hartwig/pipeline/resource/RefGenome38ResourceFiles.java
- cluster/src/main/java/com/hartwig/pipeline/resource/ResourceFiles.java
- cluster/src/main/java/com/hartwig/pipeline/snpgenotype/SnpGenotype.java
- cluster/src/test/java/com/hartwig/pipeline/snpgenotype/SnpGenotypeTest.java
- cluster/src/test/resources/smoke_test/reference/expected_output_files
- cluster/src/test/resources/smoke_test/tumor-reference/expected_output_files
- cluster/src/test/resources/smoke_test/tumor/expected_output_files
> INFRA-786 Add 31SNP output to genotype stage

- cluster/src/main/java/com/hartwig/pipeline/SomaticPipeline.java
- cluster/src/main/java/com/hartwig/pipeline/tertiary/orange/Orange.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/orange/OrangeTest.java
Apparently I hadn't merged this here yet.
> INFRA-505: Always include RUO disclaimer on Orange report

- cloudbuild-pr.yaml
- cluster/src/main/java/com/hartwig/pipeline/tools/HmfTool.java
- cluster/src/main/java/com/hartwig/pipeline/tools/VersionUtils.java
- cluster/src/test/java/com/hartwig/pipeline/smoke/SmokeTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/cuppa/CuppaTest.java
- cluster/src/test/java/com/hartwig/pipeline/tertiary/orange/OrangeTest.java
- cluster/src/test/resources/smoke_test/compar_no_differences/sample.cmp.tsv
- image/tools.cmds
> ACTIN-1520: Bump cuppa to 2.3.0

- cluster/pom.xml
- cluster/src/main/java/com/hartwig/pipeline/alignment/bwa/BwaAligner.java
- cluster/src/test/java/com/hartwig/pipeline/alignment/bwa/BwaAlignerTest.java
- pom.xml
expect jitter params and ms table when running in skip markdups mode
> Infra 1285

- cluster/src/main/java/com/hartwig/pipeline/FullPipeline.java
Otherwise, the pipeline hangs by waiting on a lock that will never release.
> DEV-4142: Mark single sample pipeline complete after crash
